changed to strict confinement
canonical/software-inventory-exporter pull request #2
Opened 2023-03-15 20:21 UTC by gabrielcocenza

- snap endpoint using snapd-api and snapd-control interface
- dpkg endpoint using system-files interface

2023-03-15 21:00 UTC, rgildein approved these changes
LGTM

2023-03-16 07:52 UTC, mkalcok requested changes
Looks good overall, just two minor suggestions.

2023-03-16 07:52 UTC, mkalcok commented on software_inventory_exporter/exporter.py
> +        logger.error("Error to list snap %s", error)
you can catch multiple exceptions in one `except` statement.
```python
    except (requests.exceptions.RequestException, KeyError) as error:
        logger.error("Error to list snap %s", error)
        raise HTTPException(status_code=500, detail="Server error") from error
```

2023-03-16 13:18 UTC, mkalcok approved these changes

2023-03-16 13:28 UTC, merged